### ISSUE TITLE
List features in readme/documentation

### ISSUE THREAD

**Issue by jbmoelker** [voorhoede/nuxt-preview-mode-module#1]
We currently only highlight a single feature of the module, while there are more. I'd suggest adding those to the readme/documentation as well. Here's an attempt:

> **Extends [Nuxt's built-in preview mode](https://nuxtjs.org/docs/features/live-preview/)**:
>
> - 🚪 Enables preview mode through routing (`?preview=true`)
> - 🔒 Secures preview mode with a (client-side) secret (`&secret=...`)
> - 👉 Enables redirect when entering preview mode (`&location=/...`)
> - 🧠 Persists preview mode through routing & page refresh using storage
> - 🎛️ Provides programmatic way to `enter()` and `exit()` preview mode
> - 🍫 Provides `<PreviewModeBar>` component to display and control preview mode

**Comment by Frankwarnaar** [comment]
Resolved in https://github.com/voorhoede/nuxt-preview-mode-module/pull/9
