### ISSUE TITLE
Correct `previewSecret` query param in docs

### ISSUE THREAD

**Issue by jbmoelker** [voorhoede/nuxt-preview-mode-module#17]
The docs don't really explain how preview mode can be enabled or disabled.

Under features it briefly mentions `&secret=...`. But the module actually only works if a `&previewSecret=...` is used.

Implementation and documentation at least needs to be aligned, but can many be improved. Suggestions:

- Enable enter and exit through query param using `?preview=true|false`
- Alternatively always enter and only require the secret
- Allow query parameter name to be configured
- Add examples/documentation on how this feature is used

**Comment by Frankwarnaar** [comment]
Resolved in https://github.com/voorhoede/nuxt-preview-mode-module/commit/e4839945d039bb3cb2827154fce51a0077977071 and https://github.com/voorhoede/nuxt-preview-mode-module/commit/ca4f156041b3c4ef1961804cda7c42603a26e69c.
