### ISSUE TITLE
Document how to enter/exit preview mode

### ISSUE THREAD

**Issue by jbmoelker** [voorhoede/nuxt-preview-mode-module#18]
Suggestions of methods to document:

- Enter preview mode via url query parameters: `?preview=true&...`
- Exit preview mode via url query parameters: `?preview=false`
- Enter preview mode via API: `this.$previewMode.enter()`
- Exit preview mode via API: `this.$previewMode.exit()`
- Exit preview mode using `<PreviewModeExitButton>`

**Comment by Frankwarnaar** [comment]
Resolved in https://github.com/voorhoede/nuxt-preview-mode-module/commit/e4839945d039bb3cb2827154fce51a0077977071
