### ISSUE TITLE
Configurable storage key

### ISSUE THREAD

**Issue by jbmoelker** [voorhoede/nuxt-preview-mode-module#2]
The [`STORAGE_KEY` is currently hardcoded](https://github.com/voorhoede/nuxt-preview-mode-module/blob/e3763f/lib/plugin.client.ts#L3):

```ts
const STORAGE_KEY = 'nuxt-datocms-preview-data';
```

Would be nice if this matches the module name by default (`'nuxt-preview-mode'`) and possibly be configurable through the module options.

**Comment by Frankwarnaar** [comment]
Resolved in https://github.com/voorhoede/nuxt-preview-mode-module/pull/6
