### ISSUE TITLE
Extend example with controls to try out the module

### ISSUE THREAD

**Issue by jbmoelker** [voorhoede/nuxt-preview-mode-module#3]
The [current example only shows the preview state](https://github.com/voorhoede/nuxt-preview-mode-module/blob/e3763fa/example/pages/index.vue#L4):

```vue
<p>Preview enabled: {{ $nuxt.isPreview }}</p>
```

The example would be a good opportunity to add some controls to also showcase the other features:

- enable preview via routing: `<a href="/?preview=true&secret=...."`
- show it doesn't work without `secret=`
- show how the `location=` option works
- add a button to show `$previewMode.enter()` enables preview mode
- add a button to show `$previewMode.exit()` exits preview mode
- add a `<PreviewModeBar />`

**Comment by Frankwarnaar** [comment]
Resolved in https://github.com/voorhoede/nuxt-preview-mode-module/pull/7 and https://github.com/voorhoede/nuxt-preview-mode-module/pull/8
