### ISSUE TITLE
Add a <PreviewModeBar> to the module

### ISSUE THREAD

**Issue by jbmoelker** [voorhoede/nuxt-preview-mode-module#4]
Add a `<PreviewModeBar>` to the module to make it easier to use the module.

Suggestion for how this could work for the consuming developer:

```vue
<template>
  <PreviewModeBar>
     Content to show in bar when preview is enabled
     <PreviewModeExitButton>
       Exit preview
     </PreviewModeExitButton>
  </PreviewModeBar>
</template>

<script>
  import { PreviewModeBar, PreviewModeExitButton } from '@voorhoede/nuxt-preview-mode-module'
</script>
```

By using some composition users can easily modify contents (like using i18n) while the functionality remains unchanged.

This would mean the `PreviewModeBar` would only need to be something like:

```vue
<template>
  <ClientOnly v-if="$nuxt.isPreview">
      <slot />
  </ClientOnly>
</template>
```

And the `PreviewModeExitButton` something like:

```vue
<template>
    <button type="button" @click="$previewMode.exit">
        <slot>Exit preview</slot>
    </button>
</template>
```

Not sure what to do with styling.

Could also just put an example component in the readme which users can customise:

```vue
<template>
  <ClientOnly v-if="$nuxt.isPreview">
    <div>
      <p>Preview mode is enabled</p>
      <button type="button" @click="$previewMode.exit">
        Exit preview
      </button>
    </div>
  </ClientOnly>
</template>
```

**Comment by Frankwarnaar** [comment]
Resolved in https://github.com/voorhoede/nuxt-preview-mode-module/commit/6a074d8bb8b90cfd21e19708cb850eff1138c957
