### ISSUE TITLE
Automatically publish packages to registry

### ISSUE THREAD

**Issue by jbmoelker** [voorhoede/nuxt-preview-mode-module#5]
Automatically publish packages to npm and GitHub package registry, so users always have access to the latest version.

We can borrow this workflow from our other packages, like this one:

https://github.com/voorhoede/vue-dato-image/blob/master/.github/workflows/npm.yml

**Comment by Frankwarnaar** [comment]
Resolved in https://github.com/voorhoede/nuxt-preview-mode-module/commit/8e776eb6838bc2b390e18f5d70280f13bf9c7f6d
